# Generated by Django 4.0.5 on 2022-12-16 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoFinalApp', '0007_delete_persona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='rol',
        ),
    ]
