# Generated by Django 4.0.5 on 2022-12-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoFinalApp', '0009_rename_perfil_avatar_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='profilePics/'),
        ),
    ]
